version: "3.8"
services:
  middle-server:
    build:
      context: ./middle-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  orca-agent:
    build:
      context: ./
      dockerfile: ClassificationDockerfile
    environment:
      - NODE_ENV=production
    restart: always
