"""Prompts for the repository summarization workflow."""

PROMPTS = {
    "system_prompt": (
        "You are an expert software architect and technical lead specializing in summarizing "
        "repositories into comprehensive documentation. You excel at analyzing codebases "
        "and creating clear, structured documentation."
    ),
    "create_branch": (
        "You need to create a feature branch for the README generation.\n"
        "Create a new branch with a descriptive name related to creating a README file.\n"
    ),
    "classify_repository": (
        "Analyze the repository structure and identify the type of repository this is.\n"
        "Use the `classify_repository` tool to report your choice.\n"
        "You must choose one of the following repository types:\n"
        "- Library/SDK: Code meant to be imported and used by other developers\n"
        "- Web App: Frontend or full-stack web application\n"
        "- API Service: Server-side application providing APIs\n"
        "- Mobile App: Native or cross-platform mobile app\n"
        "- Tutorial: Educational repository demonstrating techniques\n"
        "- Template: Starter code for new projects\n"
        "- CLI Tool: Command-line interface application\n"
        "- Framework: Foundational structure for building applications\n"
        "- Data Science: Machine learning or data analysis project\n"
        "- Plugin: Extension or module for a larger system (e.g., CMS, IDE, platform)\n"
        "- Chrome Extension: Browser extension targeting the Chrome platform\n"
        "- Jupyter Notebook: Interactive code notebooks, often for demos or research\n"
        "- Infrastructure: Configuration or automation code (e.g., Docker, Terraform)\n"
        "- Smart Contract: Blockchain smart contracts, typically written in Solidity, Rust, etc.\n"
        "- DApp: Decentralized application with both smart contract and frontend components\n"
        "- Game: Codebase for a game or game engine (2D, 3D, or browser-based)\n"
        "- Desktop App: GUI application for desktop environments (e.g., Electron, Qt, Tauri)\n"
        "- Dataset: Repository containing structured data for analysis or training\n"
        "- Other: If it doesn't fit into any of the above categories\n"
    ),
    "generate_readme_section": (
        "You are writing the {section_name} section of a README file for a repository.\n"
        "Read all files relevant to your task and generate comprehensive, clear documentation.\n"
        "The section should include the following information:\n"
        "{section_description}\n"
        "IMPORTANT: Do not assume that an existing README is correct. "
        "Create the documentation based on the codebase, using the README "
        "only as an entry point to understand the repository.\n"
    ),
    "create_pr": (
        "You are creating a pull request for the documentation you have generated:\n"
        "IMPORTANT: Always use relative paths (e.g., 'src/file.py' not '/src/file.py')\n\n"
        "Steps to create the pull request:\n"
        "1. First examine the available files to understand the implementation\n"
        "2. Create a clear and descriptive PR title\n"
        "3. Write a comprehensive PR description that includes:\n"
        "   - Description of all changes made\n"
        "   - The main features and value of the documentation\n"
    ),
    "other": (
        "Please scan the repository and generate or update a complete and professional readme_prometheus.md file "
        "for this repository.\n\n"
        "{previous_review_comments_section}\n\n"
        "Analyze the contents of the repository to infer its intent, and format the README using Markdown with "
        "clear section headers.\n\n"
        "Include the following general sections, customizing them as needed based on the repository type:\n"
        "1. **Project Overview**\n"
        "   - Describe the purpose of the project and its main functionality\n"
        "   - Summarize what the project does and who it's for\n\n"
        "2. **Getting Started**\n"
        "   - Include setup or usage instructions based on the repo's structure\n"
        "   - Mention installation steps, dependencies, and commands to run or use the project\n\n"
        "3. **Features / Capabilities**\n"
        "   - List the core features or components of the project\n"
        "   - Include relevant examples, demos, or configurations if applicable\n\n"
        "4. **Project Structure**\n"
        "   - Describe the layout of files and folders, especially any key scripts, configs, or assets\n\n"
        "5. **Technologies Used**\n"
        "   - List any major frameworks, libraries, or languages identified in the project\n\n"
        "6. **Usage Examples** (if applicable)\n"
        "   - Include example commands or steps showing how to use the project\n\n"
        "7. **License**\n"
        "   - State the license type and link to the license file\n\n"
        "Additional Notes:\n"
        "- Focus on making the README useful and descriptive, even if the project type is ambiguous\n"
        "- Use best judgment to tailor the content to the actual functionality and audience of the project\n"
        "- Avoid placeholder text and strive to extract real, useful information from the codebase"
    ),
    "review_readme_file": (
        "Review the README_Prometheus.md file in the repository and evaluate its quality and "
        "relevance to the repository.\n\n"
        "Please analyze:\n"
        "1. Is the README_Prometheus.md file related to this specific repository? (Does it describe the actual code "
        "and purpose of this repo?)\n"
        "2. Does it correctly explain the repository's purpose, features, and functionality?\n"
        "3. Is it comprehensive enough to help users understand and use the repository?\n"
        "4. Does it follow best practices for README documentation?\n\n"
        "Use the validate_implementation tool to submit your findings.\n"
        "IMPORTANT: Do not assume that an existing README is correct. "
        "Evaluate README_Prometheus.md against the codebase.\n"
        "STOP after submitting the review report."
    ),
    "previous_review_comments": ("Here are the comments from the previous review:\n"),
}
