stages:
  - test

cache:
  paths:
    - node_modules/
    - .yarn-cache/

test_job:
  stage: test
  image: node:21
  before_script:
    - yarn install --cache-folder .yarn-cache
  script:
    - yarn test 