"""Prompts for the repository summarization workflow."""

PROMPTS = {
    "system_prompt": (
        "You are an expert software architect and technical lead specializing in summarizing "
        "repositories into comprehensive documentation. You excel at analyzing codebases "
        "and creating clear, structured documentation."
    ),
    "classify_repository": (
        "Analyze the repository structure and identify the type of repository this is. "
        "You must choose one of the following repository types:\n"
        "- LIBRARY: Code meant to be imported and used by other developers\n"
        "- WEB_APP: Frontend or full-stack web application\n"
        "- API_SERVICE: Server-side application providing APIs\n"
        "- MOBILE_APP: Native or cross-platform mobile app\n"
        "- TUTORIAL: Educational repository demonstrating techniques\n"
        "- TEMPLATE: Starter code for new projects\n"
        "- CLI_TOOL: Command-line interface application\n"
        "- FRAMEWORK: Foundational structure for building applications\n"
        "- DATA_SCIENCE: Machine learning or data analysis project\n"
        "- OTHER: If it doesn't fit into any of the above categories\n\n"
        "Examine the file structure, dependencies, configuration files, and code patterns to determine the type.\n"
        "Please also identify any sub-types or specialized features of the repository.\n\n"
        "First, determine the repository type by analyzing code files and project structure.\n\n"
        "After analyzing the repository and determining its type, you MUST call the get_readme_prompt tool with "
        "the repository type as an argument (using the lowercase version of the type, e.g., 'library' not "
        "'LIBRARY').\n\n"
        "The tool will return a prompt template that will be used for README generation. You must include this "
        "template exactly as returned in your response.\n\n"
        "Return a structured response in the following format:\n"
        "{\n"
        '  "success": true,\n'
        '  "data": {\n'
        '    "repo_type": "CHOSEN_TYPE_IN_LOWERCASE",\n'
        '    "sub_types": ["sub-type1", "sub-type2"],\n'
        '    "description": "Brief description of the repository\'s purpose and why it was classified this way",\n'
        '    "prompt": "The prompt template returned by the get_readme_prompt tool"\n'
        "  }\n"
        "}"
    ),
    "generate_readme_file": (
        "Generate a comprehensive README file for the following repository:\n"
        "Repository: {repo_url}\n\n"
        "Please include:\n"
        "1. Project Overview\n"
        "   - Purpose and main functionality\n"
        "   - Key features\n"
        "2. Repository Structure\n"
        "   - Detailed breakdown of directories and their purposes\n"
        "   - Key files and their roles\n"
        "3. Technical Details\n"
        "   - Technologies used\n"
        "   - Architecture overview\n"
        "4. File Contents\n"
        "   - Specific description of each significant file\n\n"
        "Format the output in markdown, ensuring clear section headers and proper formatting."
        "Please commit and push the changes to the repository after generating the README file."
    ),
    "library": (
        "Generate a comprehensive README file for the following repository:\n"
        "Please include:\n"
        "1. Project Overview\n"
        "   - Purpose and main functionality\n"
        "   - Key features\n"
        "2. Repository Structure\n"
        "   - Detailed breakdown of directories and their purposes\n"
        "   - Key files and their roles\n"
        "3. Technical Details\n"
        "   - Technologies used\n"
        "   - Architecture overview\n"
        "4. File Contents\n"
        "   - Specific description of each significant file\n\n"
        "Format the output in markdown, ensuring clear section headers and proper formatting.\n"
        "For this LIBRARY repository, focus on:\n"
        "- API documentation and public interfaces\n"
        "- Installation and usage examples\n"
        "- Integration guides\n"
        "- Extension points\n\n"
        "Please commit and push the changes to the repository after generating the README file."
    ),
    "web_app": (
        "Generate a comprehensive README file for the following repository:\n"
        "Please include:\n"
        "1. Project Overview\n"
        "   - Purpose and main functionality\n"
        "   - Key features\n"
        "2. Repository Structure\n"
        "   - Detailed breakdown of directories and their purposes\n"
        "   - Key files and their roles\n"
        "3. Technical Details\n"
        "   - Technologies used\n"
        "   - Architecture overview\n"
        "4. File Contents\n"
        "   - Specific description of each significant file\n\n"
        "Format the output in markdown, ensuring clear section headers and proper formatting.\n"
        "For this WEB_APP repository, focus on:\n"
        "- Setup and deployment instructions\n"
        "- Configuration options\n"
        "- User flows and features\n"
        "- Frontend/backend architecture\n\n"
        "Please commit and push the changes to the repository after generating the README file."
    ),
    "api_service": (
        "Generate a comprehensive README file for the following repository:\n"
        "Please include:\n"
        "1. Project Overview\n"
        "   - Purpose and main functionality\n"
        "   - Key features\n"
        "2. Repository Structure\n"
        "   - Detailed breakdown of directories and their purposes\n"
        "   - Key files and their roles\n"
        "3. Technical Details\n"
        "   - Technologies used\n"
        "   - Architecture overview\n"
        "4. File Contents\n"
        "   - Specific description of each significant file\n\n"
        "Format the output in markdown, ensuring clear section headers and proper formatting.\n"
        "For this API_SERVICE repository, focus on:\n"
        "- API endpoints and documentation\n"
        "- Authentication mechanisms\n"
        "- Request/response formats\n"
        "- Deployment and scaling\n\n"
        "Please commit and push the changes to the repository after generating the README file."
    ),
    "mobile_app": (
        "Generate a comprehensive README file for the following repository:\n"
        "Please include:\n"
        "1. Project Overview\n"
        "   - Purpose and main functionality\n"
        "   - Key features\n"
        "2. Repository Structure\n"
        "   - Detailed breakdown of directories and their purposes\n"
        "   - Key files and their roles\n"
        "3. Technical Details\n"
        "   - Technologies used\n"
        "   - Architecture overview\n"
        "4. File Contents\n"
        "   - Specific description of each significant file\n\n"
        "Format the output in markdown, ensuring clear section headers and proper formatting.\n"
        "For this MOBILE_APP repository, focus on:\n"
        "- Platform support (iOS/Android)\n"
        "- Development setup\n"
        "- App architecture\n"
        "- Key features and screens\n\n"
        "Please commit and push the changes to the repository after generating the README file."
    ),
    "tutorial": (
        "Generate a comprehensive README file for the following repository:\n"
        "Please include:\n"
        "1. Project Overview\n"
        "   - Purpose and main functionality\n"
        "   - Key features\n"
        "2. Repository Structure\n"
        "   - Detailed breakdown of directories and their purposes\n"
        "   - Key files and their roles\n"
        "3. Technical Details\n"
        "   - Technologies used\n"
        "   - Architecture overview\n"
        "4. File Contents\n"
        "   - Specific description of each significant file\n\n"
        "Format the output in markdown, ensuring clear section headers and proper formatting.\n"
        "For this TUTORIAL repository, focus on:\n"
        "- Step-by-step instructions\n"
        "- Learning outcomes\n"
        "- Prerequisites\n"
        "- Exercises and examples\n\n"
        "Please commit and push the changes to the repository after generating the README file."
    ),
    "template": (
        "Generate a comprehensive README file for the following repository:\n"
        "Please include:\n"
        "1. Project Overview\n"
        "   - Purpose and main functionality\n"
        "   - Key features\n"
        "2. Repository Structure\n"
        "   - Detailed breakdown of directories and their purposes\n"
        "   - Key files and their roles\n"
        "3. Technical Details\n"
        "   - Technologies used\n"
        "   - Architecture overview\n"
        "4. File Contents\n"
        "   - Specific description of each significant file\n\n"
        "Format the output in markdown, ensuring clear section headers and proper formatting.\n"
        "For this TEMPLATE repository, focus on:\n"
        "- Getting started guide\n"
        "- Customization options\n"
        "- Architecture decisions\n"
        "- Use cases\n\n"
        "Please commit and push the changes to the repository after generating the README file."
    ),
    "cli_tool": (
        "Generate a comprehensive README file for the following repository:\n"
        "Please include:\n"
        "1. Project Overview\n"
        "   - Purpose and main functionality\n"
        "   - Key features\n"
        "2. Repository Structure\n"
        "   - Detailed breakdown of directories and their purposes\n"
        "   - Key files and their roles\n"
        "3. Technical Details\n"
        "   - Technologies used\n"
        "   - Architecture overview\n"
        "4. File Contents\n"
        "   - Specific description of each significant file\n\n"
        "Format the output in markdown, ensuring clear section headers and proper formatting.\n"
        "For this CLI_TOOL repository, focus on:\n"
        "- Command usage and examples\n"
        "- Installation instructions\n"
        "- Configuration options\n"
        "- Input/output formats\n\n"
        "Please commit and push the changes to the repository after generating the README file."
    ),
    "framework": (
        "Generate a comprehensive README file for the following repository:\n"
        "Please include:\n"
        "1. Project Overview\n"
        "   - Purpose and main functionality\n"
        "   - Key features\n"
        "2. Repository Structure\n"
        "   - Detailed breakdown of directories and their purposes\n"
        "   - Key files and their roles\n"
        "3. Technical Details\n"
        "   - Technologies used\n"
        "   - Architecture overview\n"
        "4. File Contents\n"
        "   - Specific description of each significant file\n\n"
        "Format the output in markdown, ensuring clear section headers and proper formatting.\n"
        "For this FRAMEWORK repository, focus on:\n"
        "- Core concepts and architecture\n"
        "- Extension points\n"
        "- Integration examples\n"
        "- Best practices\n\n"
        "Please commit and push the changes to the repository after generating the README file."
    ),
    "data_science": (
        "Generate a comprehensive README file for the following repository:\n"
        "Please include:\n"
        "1. Project Overview\n"
        "   - Purpose and main functionality\n"
        "   - Key features\n"
        "2. Repository Structure\n"
        "   - Detailed breakdown of directories and their purposes\n"
        "   - Key files and their roles\n"
        "3. Technical Details\n"
        "   - Technologies used\n"
        "   - Architecture overview\n"
        "4. File Contents\n"
        "   - Specific description of each significant file\n\n"
        "Format the output in markdown, ensuring clear section headers and proper formatting.\n"
        "For this DATA_SCIENCE repository, focus on:\n"
        "- Data processing pipelines\n"
        "- Model architecture\n"
        "- Training and evaluation\n"
        "- Inference and deployment\n\n"
        "Please commit and push the changes to the repository after generating the README file."
    ),
    "other": (
        "Generate a comprehensive README file for the following repository:\n"
        "Please include:\n"
        "1. Project Overview\n"
        "   - Purpose and main functionality\n"
        "   - Key features\n"
        "2. Repository Structure\n"
        "   - Detailed breakdown of directories and their purposes\n"
        "   - Key files and their roles\n"
        "3. Technical Details\n"
        "   - Technologies used\n"
        "   - Architecture overview\n"
        "4. File Contents\n"
        "   - Specific description of each significant file\n\n"
        "Format the output in markdown, ensuring clear section headers and proper formatting.\n"
        "Customize the content based on the repository's purpose.\n\n"
        "Please commit and push the changes to the repository after generating the README file."
    ),
}
