"""Prompts for the repository summarization workflow."""

PROMPTS = {
    "system_prompt": (
        "You are an expert software architect and technical lead specializing in summarizing "
        "repositories into comprehensive documentation. You excel at analyzing codebases "
        "and creating clear, structured documentation."
    ),
    "classify_repository": (
        "Analyze the repository structure and identify the type of repository this is.\n"
        "Use the `classify_repository` tool to report your choice.\n"
        "You must choose one of the following repository types:\n"
        "- Library/SDK: Code meant to be imported and used by other developers\n"
        "- Web App: Frontend or full-stack web application\n"
        "- API Service: Server-side application providing APIs\n"
        "- Mobile App: Native or cross-platform mobile app\n"
        "- Tutorial: Educational repository demonstrating techniques\n"
        "- Template: Starter code for new projects\n"
        "- CLI Tool: Command-line interface application\n"
        "- Framework: Foundational structure for building applications\n"
        "- Data Science: Machine learning or data analysis project\n"
        "- Plugin: Extension or module for a larger system (e.g., CMS, IDE, platform)\n"
        "- Chrome Extension: Browser extension targeting the Chrome platform\n"
        "- Jupyter Notebook: Interactive code notebooks, often for demos or research\n"
        "- Infrastructure: Configuration or automation code (e.g., Docker, Terraform)\n"
        "- Smart Contract: Blockchain smart contracts, typically written in Solidity, Rust, etc.\n"
        "- DApp: Decentralized application with both smart contract and frontend components\n"
        "- Game: Codebase for a game or game engine (2D, 3D, or browser-based)\n"
        "- Desktop App: GUI application for desktop environments (e.g., Electron, Qt, Tauri)\n"
        "- Dataset: Repository containing structured data for analysis or training\n"
        "- None: If repository is not programming related\n"
        "- Other: If it doesn't fit into any of the above categories\n"
    ),
    "classify_language": (
        "Analyze the repository and identify the primary programming language(s) used.\n"
        "Use the `classify_language` tool to report your choice.\n"
        "You must choose one or more of the following languages:\n"
        "- Python\n"
        "- JavaScript/TypeScript\n"
        "- Java\n"
        "- C/C++\n"
        "- Go\n"
        "- Rust\n"
        "- Ruby\n"
        "- PHP\n"
        "- Swift\n"
        "- Kotlin\n"
        "- Scala\n"
        "- R\n"
        "- Shell Script\n"
        "- None: If repository is not programming related\n"
        "- Other: If it doesn't fit into any of the above categories\n"
    ),
    "classify_test_framework": (
        "Analyze the repository and identify the test framework(s) used.\n"
        "Use the `classify_test_framework` tool to report your choice.\n"
        "You must choose one or more of the following test frameworks:\n"
        "- pytest (Python)\n"
        "- unittest (Python)\n"
        "- Jest (JavaScript)\n"
        "- Mocha (JavaScript)\n"
        "- JUnit (Java)\n"
        "- TestNG (Java)\n"
        "- Go testing (Go)\n"
        "- RSpec (Ruby)\n"
        "- PHPUnit (PHP)\n"
        "- XCTest (Swift)\n"
        "- Kotest (Kotlin)\n"
        "- None: If no test framework is detected\n"
        "- Other: If it doesn't fit into any of the above categories\n"
    ),
}
