version: "3.8"

services:
  middle-server:
    build:
      context: ../middle-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  orca-agent:
    build:
      context: ../summarizer/classification-orca/orca-agent
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: always
